# Generated by Django 4.2.6 on 2023-11-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reccdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100)),
                ('uk', models.IntegerField()),
                ('spain', models.IntegerField()),
                ('france', models.IntegerField()),
                ('netherland', models.IntegerField()),
                ('austria', models.IntegerField()),
                ('italy', models.IntegerField()),
                ('business', models.IntegerField()),
                ('leisure', models.IntegerField()),
                ('solo', models.IntegerField()),
                ('couple', models.IntegerField()),
                ('group', models.IntegerField()),
            ],
        ),
    ]
