# Generated by Django 4.2.6 on 2023-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_reccdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reccdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='reccdb',
            name='hotelname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
